- hosts: terraform-ansible
  tasks:
  - name: Instalando infraestrutura
    apt:
      pkg:
      - python3
      - git
      - nginx
      - pip
      update_cache: yes
    become: yes
  - name: Instalando flask
    pip: name=flask
    become: yes
  - name: Instalando gunicorn
    pip: name=gunicorn
    become: yes
  - name: Configurando nginx
    copy:
      src: nginx.conf
      dest: /etc/nginx/sites-available/teste
      force: yes
    check_mode: yes
    notify: restart nginx
  - name: Criando link simbolico
    file:
      src: /etc/nginx/sites-available/teste
      dest: /etc/nginx/sites-enabled/teste
      state: link
    become: yes
    notify: restart nginx
  - name: Clonando repositorio
    git:
      repo: 'https://github.com/marcosvile/portfolio.git'
      dest: /home/ubuntu/portfolio
      clone: yes
      force: yes
  - name: Iniciando aplicação
    shell: "cd /home/ubuntu/portfolio; nohup flask run --host=0.0.0.0 --port=8080 &"
